// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoodleMaps.Data;

#nullable disable

namespace NoodleMaps.Migrations
{
    [DbContext(typeof(NoodleDbContext))]
    [Migration("20251208042541_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("NoodleMaps.Models.NoodleEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("OverallScore")
                        .HasColumnType("REAL");

                    b.Property<int>("ScoreA_Soup")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScoreB_Noodle")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScoreC_Topping")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScoreD_Atmosphere")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScoreE_CostPerf")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NoodleEntry");
                });
#pragma warning restore 612, 618
        }
    }
}
